-- SAK-13474 Increase length of announcement channel to 255 chars
ALTER TABLE ANNOUNCEMENT_CHANNEL MODIFY COLUMN CHANNEL_ID VARCHAR(255);
ALTER TABLE ANNOUNCEMENT_MESSAGE MODIFY COLUMN CHANNEL_ID VARCHAR(255);
