-- SAK-13474 Increase length of announcement channel to 255 chars
ALTER TABLE ANNOUNCEMENT_CHANNEL MODIFY (CHANNEL_ID VARCHAR2(255));
ALTER TABLE ANNOUNCEMENT_MESSAGE MODIFY (CHANNEL_ID VARCHAR2(255)); 
